spring:
  primary:
    datasource:
      password: postgres_write
      username: postgres_write
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
  replica:
    datasource:
      password: postgres_read
      username: postgres_read
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres

  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false